export const LOGIN_CHANGE = 'LOGIN_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';

export const LOGIN_ERROR_CHANGE = 'LOGIN_ERROR_CHANGE';
export const PASSWORD_ERROR_CHANGE = 'PASSWORD_ERROR_CHANGE';
